[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'digitaltoad/vim-jade'

#[[plugins]]
#repo = 'Shougo/unite.vim'
#
#[[plugins]]
#repo = 'thinca/vim-quickrun'
#
#[[plugins]]
#repo = 'shougo/vimshell'
#
#[[plugins]]
#repo = 'kannokanno/previm'
#
#[[plugins]]
#repo = 'tyru/open-browser.vim'
#
